import Head from 'next/head'

export default function Layout({title, children}) {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" conent="Generated by create next app" />
                <link rel="icon" href="/favitcon.ico" />
            </Head>
            {children}
        </>
    )
}
